<div class="container">
  <div class="d-flex justify-content-center mt-5">
    <div class="card" style="width: 36rem;">
      <div class="card-body">

        <div class="d-flex justify-content-center">
          <img src="/img/twitter_logo.png" />
        </div>

        <div class="row">
          <div class="col">
            <h2>Atualizar Nome</h2>
          </div>
        </div>

        <div class="row">
          <div class="col">
            
            <form action="/" method="post">
              <div class="form-group">
                <input name="nome"  type="text" class="form-control" placeholder="Nome">
              </div>
              
      
              <button type="submit" class="btn btn-primary btn-block">Atualizar</button>
 
            </form>


            

          </div>
        </div>

      </div>
    </div>
  </div>
</div>



    
  